name: OnyxMusic Feed Guncelleyici

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch: 

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: node scraper.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🚀 Otomatik Güncelleme: feed.json ve Orijinal Kapaklar yenilendi!"
          file_pattern: feed.json package.json
