name: Update Feed

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 8 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Google Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome Path
        run: echo "${{ steps.setup-chrome.outputs.chrome-path }}"

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: node scraper.js

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Feed and Playlist Images Updated"
          # DEĞİŞEN KISIM BURASI: Robot artık hem feed.json dosyasını hem de images klasöründeki yeni resimleri hafızaya alır.
          file_pattern: 'feed.json images/*'
