name: Update Feed

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 8 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Remove Puppeteer Cache
        run: rm -rf ~/.cache/puppeteer

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        run: node scraper.js
